# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

language: go

os:
- linux
- osx

go:
- "1.13"

git:
  depth: 3

go_import_path: sigs.k8s.io/application

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
-

before_script:
# create Kind cluster
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make e2e-setup; fi

script:
# Ensure Build works and unit tests pass
- make
# Run e2e tests
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make e2e-test; fi

after_script:
# Delete Kind cluster
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make e2e-cleanup; fi

# TBD. Suppressing for now.
notifications:
  email: false
